language: python
python:
  - 3.6
install:
  - pip install codecov
  - pip install flake8
  - pip install .
before_script:
  - flake8 .
script:
  - coverage run paw/tests/__init__.py
after_success:
  codecov