language: python
python:
  - 3.6
install:
  - pip install codecov
  - pip install flake8
  - pip install mock
  - pip install -r requirements.txt
  - pip install .
before_script:
  - sudo apt-get install -y dos2unix
  - find . -type f -print0 | xargs -0 dos2unix --
  - flake8 .
script:
  - coverage run -m unittest discover
after_success:
  codecov