language: python
apt:
  packages:
    - dos2unix
python:
  - 3.6
install:
  - pip install codecov
  - pip install flake8
  - pip install mock
  - pip install -r requirements.txt
  - pip install .
before_script:
  - find /path -type f -print0 | xargs -0 dos2unix --
  - flake8 .
script:
  - coverage run -m unittest discover
after_success:
  codecov